### ISSUE TITLE
Issuance Date Question

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#11]
Up for discussion:

It looks like the issuance date changes when the credential is claimed. Should we consider the issuance data is the awarded date and have that provided in the csv? If the credential is re-issued, we'd want the original date. Also, the VC proof has a created date that could change whenever a VC signed. Then there could be an issuance date that stays the same and a created date that changes.

**Comment by TaylorBeeston** [comment]
I agree! I'm going to change the logic to first prefer an `awardedDate` or `Awarded Date` column in the CSV, and fall back to the `updatedAt` field for the Credential object we store in Mongo if there isn't one (current behavior)!
