### ISSUE TITLE
SMTP Settings and From Email Question

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#12]
Where are the SMTP settings and how can the from email be changed?

**Comment by TaylorBeeston** [comment]
SMTP Settings are currently handled by environment variables (in code [here](https://github.com/learningeconomy/admin-dashboard/blob/89d407901c7012907fb4d38a45f0e8b70942a0c2/services/payload/src/payload.config.ts#L29-L45))

I'm going to update our data model to allow setting a from per email template as well as per batch. They will just be in the forms where the logic will first prefer batch from, fallback to email template from if there isn't one, then fall back to a from set by an environment variable, then fall back to what it currently is ('Learning Economy <beestontaylor@learningeconomy.io>', found [here](https://github.com/learningeconomy/admin-dashboard/blob/89d407901c7012907fb4d38a45f0e8b70942a0c2/services/payload/src/jobs/queue.server.ts#L69)

**Comment by kayaelle** [comment]
Good idea. I suspect that will be very useful to some.

**Comment by TaylorBeeston** [comment]
This is now live as of [57165f4](https://github.com/learningeconomy/admin-dashboard/commit/57165f4802dbdbbe640c3d36f2b940dcfb2b9604)
