### ISSUE TITLE
Add Way to Return to Upload & Manage Earner Information After Viewing Single Earner Details

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#22]
On the Upload & Manage Earner Information when clicking on the "View Details" action you are taken to a page to view the data for that specific earner. There is no way to navigate back to the Upload & Manage Earner Information screen without hitting the browser back button.

A back button is needed or perhaps we consider a different way to view the earner details without leaving the Upload & Manage Earner Information screen.

**Comment by TaylorBeeston** [comment]
Partially fixed by 3801d351ab54a61ba1c9b8177cb5be9576dd8f64

Now if you click view details on a credential, the browser back button will take you to the same spot. Just need to manually add a custom back button that will appear when that is the case

**Comment by TaylorBeeston** [comment]
Fixed by 97f58f1a464dda47f5d8509da238b33628ac07d5
