### ISSUE TITLE
Extra Fields in Earner Details View

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#23]
The earner detail view displays Credential Name, Earner Name, Email Address but also Extra fields which include credentialName, earnerName, and emailAddress. What is meant by "extra fields" and what should be in here? What if we call this something like "Credential Fields" with some text that explains that these fields can be updated and to click the save button below (or maybe that message gets displayed at the top of the page?

Example earner details: https://dashboard.bridge.learncard.com/admin/collections/credential/6548fdc96feceffa5d669600

**Comment by goblincore** [comment]
@kayaelle just to clarify, the extrafields field shows arbitrary fields that are not defined in the schema, eg credentialName, earnerName and emailAddress are defined explicity in the db schema but all other fields are considered extraFields. we can change the display name and add some additional text.

**Comment by goblincore** [comment]
Changes display label for extraFields field to "Credential Fields" and adds description below
https://github.com/learningeconomy/admin-dashboard/commit/c0d52f2d45834882e95dc651fc7352007863b911
