### ISSUE TITLE
issuanceDate in Earner Details View Extra Fields

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#24]
For this earner: https://dashboard.bridge.learncard.com/admin/collections/credential/6548fdc96feceffa5d669600

The issuanceDate was included in the batch's csv file although the when the csv file was uploaded, the orange warning displayed that the template was missing that field. Since issuanceDate is a special field, Could we tell the user that it is a special field that is populated by the system and then ignore it?

**Comment by goblincore** [comment]
This adds a warning message on the upload CSV step, it is unclear if you wanted to add a message there or somewhere else. I suppose we can add another message on the credential record view too but it is not clear from the issue description.
https://github.com/learningeconomy/admin-dashboard/commit/93148f467475f485de19fb40d8658fa8b0249fc2
