### ISSUE TITLE
Email Missing Fields

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#31]
In this email template: https://dashboard.bridge.learncard.com/admin/collections/email-template/653991c5d3fa730571cb80a8

The first sentence begins with: <p>Congratulations on earning your {{degreeType}} in {{ subject }}.</p> but degreeType and subject are missing in the email. Can we check that:

1. any field included in the email template is also in the credential template
2. any field in the email and credential template displays in the email?

**Comment by goblincore** [comment]
@kayaelle putting up a fix for this - the reason this was happening is we changed the template insertion logic to be more generalized but we didn't take into account that the templating insertion function doesn't handle nested fields very well (degreeType and subject are a subproperty of the  'extraFields' field) so they were not being inserted properly

**Comment by TaylorBeeston** [comment]
Fixed by 9f3580e3d0efeb9c65fe275fa56fbeda26a1c0b4
