### ISSUE TITLE
Number of batches issued static title

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#35]
Upon installing a new dashboard, the Issuance Overview title says there are 25 batches issued when none have been issued on this  install yet.

<img width="1471" alt="Screen Shot 2023-11-13 at 4 00 42 PM" src="https://github.com/learningeconomy/admin-dashboard/assets/206059/6814f75f-8c18-4530-8353-7e7f80d8be1c">

**Comment by kayaelle** [comment]
Same with Credential Templates and Email Templates titles

<img width="1498" alt="Screen Shot 2023-11-13 at 4 03 05 PM" src="https://github.com/learningeconomy/admin-dashboard/assets/206059/b836677a-54b5-4836-a573-5cb2891adaa7">

<img width="1521" alt="Screen Shot 2023-11-13 at 4 03 24 PM" src="https://github.com/learningeconomy/admin-dashboard/assets/206059/d4b64999-355a-4b1f-82cf-0eafb86a3814">

**Comment by goblincore** [comment]
@kayaelle yeah this is an easy fix will have it up shortly and let you know

**Comment by goblincore** [comment]
fixed in https://github.com/learningeconomy/admin-dashboard/pull/39
