### ISSUE TITLE
[untitled] on create new user form

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#36]
It says [Untitled] when creating a new user. This looks ot be the spot where the user name appears once that user has been created.

Can we remove that on the new creation state or instead display the text "Create a New User"?

<img width="1307" alt="Screen Shot 2023-11-13 at 4 23 37 PM" src="https://github.com/learningeconomy/admin-dashboard/assets/206059/3764857e-565b-460d-96f1-e9b88054f3fc">

**Comment by TaylorBeeston** [comment]
Fixed by 83939beda8d49f58298d2980347526ed903910c6
