### ISSUE TITLE
Credential template in batch shows credential id instead of credential template name

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#37]
<img width="1556" alt="Screen Shot 2023-11-14 at 12 16 17 PM" src="https://github.com/learningeconomy/admin-dashboard/assets/206059/10635aa9-c6b6-48a1-87de-17a38a897dca">

**Comment by goblincore** [comment]
@kayaelle it seems like the list is populating it with both drafts and published ones - so the ones that are IDS are draft ones that dont seem to have any title information so it is falling back to the ID. but yeah I guess I should change it so it just shows published ones 🤔 thought i feel like that's what it should do by default but I'll take a look

**Comment by goblincore** [comment]
@kayaelle this should be fixed now in next deploy. For now we have disabled draft status for credential and email templates as it was causing some issues and this simplifies things, that change also fixes this
