### ISSUE TITLE
Batch csv upload issues

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#38]
Using a csv template provided when the credential is created and after validating the csv file with data on the credential template interface, when uploading the csv file in the batch, get warnings that degreeType and subject are not variables in the credentialTemplate. For this test used a new credential template: https://dashboard.bridge.learncard.com/admin/collections/credential-template/6553ab0f91d835948201c2c1

When this warning is displayed, hit continue, choose email template (DCC Demo Degree: https://dashboard.bridge.learncard.com/admin/collections/email-template/6553adce91d835948201c644) and get a green validation confirmation message.

Hit continue and there are no credentials listed in the "Credentials From CSV" section.

Hit back button twice, remove each earner. Try to choose file again, dialog to choose file opens and after file is chosen, nothing happens. Continue button faded out. Click back arrow and then continue, upload csv file again and same result. 

Go back to issued batches page, select [Demo DCC Bachelor's Degree Test 1](https://dashboard.bridge.learncard.com/admin/collections/credential-batch/6553ab4391d835948201c32c), continue to upload csv file, choose file, same warning. Click continue to confirmation screen and no credentials listed in the "Credentials From CSV" section. Click back arrow twice, upload the csv again (this time don't remove earners), nothing happens. Save draft, open up same batch and go to csv upload, after uploading the csv, the two earners are added again so that there are 4 (warning still displaying), on confirmation page, two of the earners displaying in "Credentials From CSV" section.

<img width="1570" alt="Screen Shot 2023-11-14 at 12 31 52 PM" src="https://github.com/learningeconomy/admin-dashboard/assets/206059/602afe2a-8cf2-4419-91ba-9de931a555c7">

[Demo DCC Bachelor's Degree.csv](https://github.com/learningeconomy/admin-dashboard/files/13352568/Demo.DCC.Bachelor.s.Degree.csv)

**Comment by goblincore** [comment]
@kayaelle Was able to confirm there is an issue on the confirmation page displaying the list, however they are there - I can look into it but if you upload and it shows the list on the Upload CSV step and then on the confirmation screen it is empty, they are there and it will send, I just tried:

<img width="1288" alt="Screenshot 2023-11-14 at 1 23 32 PM" src="https://github.com/learningeconomy/admin-dashboard/assets/18289875/3c7402b6-1bd2-4e3a-b097-a740648adfb2">

**Comment by kayaelle** [comment]
Hi @goblincore - here's a screen capture of what I'm seeing. This is in Chrome Version 118.0.5993.117.


Uploading Screen Recording 2023-11-14 at 1.31.30 PM.mov…

**Comment by TaylorBeeston** [comment]
@kayaelle So this is a compound problem with three underlying issues:
- [x] Credential Templates that are drafts don't actually expose their JSON to the Upload CSV step, meaning it thinks there _are_ no fields that the template is using
    - I fixed this by just disabling drafts altogether for credential templates! I also fixed this right away for you here by publishing that template!
- [ ] The two displays for credentials make two different requests to get their data, and only the first one is refetched when adding/deleting credentials
- [ ] The input element where you upload the CSV is listening for an `onChange` event when you upload a file. Meaning if you upload the same file twice, it doesn't technically "change", and so `onChange` never fires the second time

**Comment by kayaelle** [comment]
These fixes are working as expected @TaylorBeeston. I think we can close this issue now. Thanks!
